[build]
  functions = "netlify/functions"
  publish = "build"  # El directorio de publicaci√≥n, puede ser "dist" o "public" dependiendo de tu proyecto
  command = "npm run build"  # El comando para construir tu proyecto

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200